### ISSUE TITLE
New Instagram API

### ISSUE THREAD

**Issue by Liechtenecker** [Liechtenecker/instapress#5]
So this is the most important one: we need to connect the plugin with the new instagram API.
Maybe before we look at the other issues.

I haven't worked with the new API before, so I will take a look at it. If it's neccessary to create any app tokens (like with Twitter Apps) I will create them and let you know

**Comment by dejliglama** [comment]
Any updates on this - I'm not a developer, but perhaps I can throw in a $-bone of sorts, not much but would love to see this work :)

**Comment by QuentinMoss** [comment]
What functions are not working properly? I'm able to authenticate and pull my personal feed with the shortcode.

**Comment by timvanrooyen** [comment]
There are some issues when specifying a particular hashtag (not all images appear) and also when combining a specific username and hashtag. 

Paging has been the major issue for me. More than 33 image do not page.  Back and forward buttons appear but paging does not work. 

Regards

Tim van Rooyen

**Comment by Liechtenecker** [comment]
I spend some time now testing the plugin and it turns out @mossy1 is totally right - thank you

Tags and usernames are working perfectly for me but I think this needs more tests (I will create an issue for that).
An issue for the paging problem already exists.

Cheers ;)
